Added support for Statamic 4.0
justkidding96/statamic-aardvark-seo pull request #160
Opened 2023-05-15 18:13 UTC by justkidding96

2023-05-16 08:22 UTC, mkwia commented
Addresses #159. Need to test and tag new release for v4.

2023-05-16 08:23 UTC, mkwia commented
Thank you for your PR @justkidding96 . The team will review this shortly

2023-05-19 07:15 UTC, geertjanknapen1 commented
Any updates?

2023-05-19 11:15 UTC, geertjanknapen1 requested changes

2023-05-19 11:15 UTC, geertjanknapen1 commented on src/Listeners/AppendEntrySeoFieldsListener.php
> +            $contents[$on_page_key']['SEO'] = $on_page_fields;
There's a `'` after `$on_page_key` there. That will break.

2023-05-19 11:18 UTC, geertjanknapen1 requested changes

2023-05-19 11:18 UTC, geertjanknapen1 commented on src/Listeners/AppendTermSeoFieldsListener.php
> +            $on_page_key = (array_key_exists('tabs', $on_page_bp->contents() ? 'tabs' : 'sections');
missing `)` after `(array_key_exists('tabs', $on_page_bp->contents()`

is now;
`$on_page_key = (array_key_exists('tabs', $on_page_bp->contents() ? 'tabs' : 'sections');`
should be;
`$on_page_key = (array_key_exists('tabs', $on_page_bp->contents()) ? 'tabs' : 'sections');`

2023-05-19 11:25 UTC, joshuanoyes commented
Hi @justkidding96, thanks for the PR!

Happy to merge this to acknowledge your contribution but it's possible we'll ultimately go with simply accessing `tabs` rather than `sections` as this is caused by a big renaming effort in Statamic 4.

We're looking to get V4 support out ASAP - I'll confirm later today :+1:

2023-05-19 11:27 UTC, joshuanoyes commented
Thanks for the review @geertjanknapen1 :slightly_smiling_face:

2023-05-19 15:18 UTC, merged